### ISSUE TITLE
Multiple sensors or triggers

### ISSUE THREAD

**Issue by vladosam** [rainu/mqtt-executor#2]
Hello, can i create multiple sensors for reading some bash script output like this? Or i have to use multi_sensor? Also can i create multiple triggers? Thanks.
```
  "sensor": [{
    "name": "Free Memory",
    "topic": "tele/__DEVICE_ID__/memory/free",
    ...
    "command": {
      "name": "/bin/sh",
      "arguments": [
        "-c",
        "cat /proc/meminfo | grep MemFree | cut -d\\: -f2 | sed 's/ //g' | grep -o [0-9]*"
      ]
    }
  }],
  "sensor": [{
    "name": "My Script",
    "topic": "tele/__DEVICE_ID__/my/script",
    ...
    "command": {
      "name": "/bin/sh",
      "arguments": [
        "-c",
        "/usr/local/bin/myscript"
      ]
    }
  }],
```

**Comment by rainu** [comment]
Hey .. sorry for late response. If i understand you correctly you want to add multiple sensors in your configuration. So lets say you want configure a sensor for *my-first-script* and a sensor for *my-second-script*. Then your configuration has to look like this:

```
{
  "sensor": [{
    "name": "First Script",
    "topic": "tele/__DEVICE_ID__/first",
    "command": {
      "name": "/path/to/my-first-script"
    }
  },{
    "name": "Second Script",
    "topic": "tele/__DEVICE_ID__/second",
    "command": {
      "name": "/path/to/my-second-script",
      "arguments": [ "firstArgument" ]
    }
  }]
}
```
The difference between **sensor** and **multi_sensor** is that the multisensor-script-output will be used to split into multiple values (each value is its own message).

**Comment by vladosam** [comment]
Thanks for reply, but i created my own mqtt sensor with bash script. Maybe in the future i'll use mqtt-executor again. Thanks.
